# Generated by Django 2.0.2 on 2018-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pic',
            field=models.CharField(default='no_image.jpg', max_length=255),
        ),
    ]
