# Generated by Django 2.0.2 on 2018-07-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='desc',
            new_name='description',
        ),
    ]
