# Generated by Django 2.0.2 on 2018-07-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetailskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
