# Generated by Django 2.0.2 on 2018-07-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_skill', '0002_auto_20180704_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailskill',
            old_name='skill_exam_detail',
            new_name='detail_skill',
        ),
    ]
